### ISSUE TITLE
UTF validation

### ISSUE THREAD

**Issue by JakobOvrum** [s-ludwig/std_data_json#1]
[From the RFC thread](http://forum.dlang.org/post/m1fvjp$ksh$1@digitalmars.com):
>There is also still one pending change that I didn't finish yet; the optional UTF input validation (never validate "string" inputs, but do validate "ubyte[]" inputs).

**Comment by s-ludwig** [comment]
This commit was from my stash list, fixed to pass the unit tests. Since I've written this months ago, I'm not completely sure if something is still missing, but it looks complete.
