### ISSUE TITLE
minor fix to docs

### ISSUE THREAD

**Issue by Laeeth** [s-ludwig/std_data_json#6]
on this page:
http://s-ludwig.github.io/std_data_json/stdx/data/json/parser/parseJSONStream.html

This link is broken:
http://s-ludwig.github.io/std_data_json/stdx/data/json/parser/JSONParserNode.Kind.html

**Comment by s-ludwig** [comment]
Changed the file name scheme to avoid case issues on Windows. New URLs:
http://s-ludwig.github.io/std_data_json/stdx/data/json/parser/parse_json_stream.html
http://s-ludwig.github.io/std_data_json/stdx/data/json/parser/json_parser_node.kind.html
